# Generated by Django 5.1.7 on 2025-04-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_client_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='inquiry_type',
            field=models.CharField(default='Study', max_length=50),
            preserve_default=False,
        ),
    ]
