# Generated by Django 5.1.7 on 2025-04-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_client_inquiry_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='inquiry_type',
            new_name='visa_type',
        ),
    ]
