# Generated by Django 5.1.7 on 2025-04-24 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sales', '0005_client_assigned_date_client_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='client',
        ),
        migrations.AddField(
            model_name='voucher',
            name='account_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='account_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='category',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Service', 'Service'), ('Salary', 'Salary'), ('Manual', 'Manual')], max_length=50),
        ),
    ]
