# Generated by Django 5.1.7 on 2025-04-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_client_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
