# Generated by Django 5.1.7 on 2025-05-10 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plateform', models.CharField(choices=[('Facebook', 'Facebook')], max_length=15)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Running', 'Running'), ('Paused', 'Paused')], default='Draft', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('daily_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('optimization_goal', models.CharField(max_length=50)),
                ('billing_event', models.CharField(max_length=50)),
                ('bid_strategy', models.CharField(max_length=50)),
                ('fb_adset_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adsets', to='marketing.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='AdCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('link', models.URLField()),
                ('call_to_action', models.CharField(max_length=50)),
                ('fb_creative_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='marketing.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fb_ad_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='PAUSED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.adcreative')),
                ('adset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.adset')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='marketing.campaign')),
            ],
        ),
    ]
