# Generated by Django 5.1.7 on 2025-05-10 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_user_last_seen_user_online_status_delete_userstatus'),
        ('marketing', '0002_campaign_adset_adcreative_ad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='campaign_id',
            new_name='fb_campaign_id',
        ),
        migrations.AddField(
            model_name='campaign',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='company.branch'),
            preserve_default=False,
        ),
    ]
