# Generated by Django 5.1.7 on 2025-05-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_rename_campaign_id_campaign_fb_campaign_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcreative',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ad_creatives/'),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='image_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adcreative',
            name='call_to_action',
            field=models.CharField(default='LEARN_MORE', max_length=50),
        ),
    ]
