# Generated by Django 5.1.7 on 2025-05-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_adcreative_image_adcreative_image_hash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='fb_ad_id',
            new_name='ad_id',
        ),
        migrations.RenameField(
            model_name='adcreative',
            old_name='fb_creative_id',
            new_name='creative_id',
        ),
        migrations.RenameField(
            model_name='adset',
            old_name='fb_adset_id',
            new_name='adset_id',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='fb_campaign_id',
            new_name='campaign_id',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='plateform',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram')], max_length=15),
        ),
    ]
