# Generated by Django 5.1.7 on 2025-04-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('company', '0006_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='access_level',
        ),
        migrations.AddField(
            model_name='user',
            name='access_level',
            field=models.ManyToManyField(blank=True, related_name='users', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('counsellor', 'Counsellor'), ('marketing', 'Marketing'), ('accountant', 'Accountant'), ('sales representative', 'Sales Representative')], default='accountant', max_length=20),
        ),
    ]
