# Generated by Django 5.1.7 on 2025-04-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_remove_employee_access_level_user_access_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('counsellor', 'Counsellor'), ('marketing', 'Marketing'), ('accountant', 'Accountant'), ('sales representative', 'Sales Representative')], default='accountant', max_length=20),
        ),
    ]
