# Generated by Django 5.1.7 on 2025-04-23 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('team manager', 'Team Manager'), ('sales representative', 'Sales Representative'), ('counsellor', 'Counsellor'), ('marketing', 'Marketing'), ('accountant', 'Accountant')], default='accountant', max_length=20),
        ),
    ]
