# Generated by Django 5.1.7 on 2025-04-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_employee_created_by_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('team manager', 'Team Manager'), ('sales representative', 'Sales Representative'), ('counsellor', 'Counsellor'), ('marketing', 'Marketing'), ('accountant', 'Accountant')], default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='access_level',
            field=models.ManyToManyField(blank=True, related_name='users', to='company.accesslevel'),
        ),
    ]
