# Generated by Django 5.1.7 on 2025-05-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_useractivitylog_userstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='online_status',
            field=models.CharField(choices=[('online', 'Online'), ('idle', 'Idle'), ('offline', 'Offline')], default='offline', max_length=10),
        ),
        migrations.DeleteModel(
            name='UserStatus',
        ),
    ]
