# Generated by Django 5.1.7 on 2025-04-24 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sales', '0005_client_assigned_date_client_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.PositiveIntegerField(null=True)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('account_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='sales.voucher')),
            ],
        ),
    ]
